<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hierarchical_multiagent_langgraph</name>
  <version>1.0.0</version>
  <description>Hierarchical multi-agent system where a Supervisor coordinates multiple Single-Purpose Agents (SPAs) to execute complex tasks.</description>
  <maintainer email="ajtudela@gmail.com">Alberto Tudela</maintainer>
  <license>TODO: License declaration</license>
  <author email="ajtudela@gmail.com">Alberto Tudela</author>
  <author email="opfernandez@uma.es">Óscar Pons Fernández</author>
  <author email="jgaleas@uma.es">José Galeas Merchán</author>

  <depend>rclpy</depend>
  <depend>langgraph_base_ros</depend>
  <depend>llm_interactions_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>audio_common_msgs</depend>
  <depend>object_with_region</depend>
  <depend>semantic_navigation_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>ament_xmllint</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
